clustering:
  algo: kmeans
  n_clusters: 4
  random_state: 42
heading_rules:
  top_n_clusters: 3
  min_font_diff: 1.2   # separate if size ratio ≥ 1.2
ignore_patterns:
  - "^Page \\d+"       # drop headers/footers
  - "^Figure \\d+